-- =============================================================================
-- 019-actor-arke-membership.sql — REMOVED
-- =============================================================================
--
-- This migration was gutted when the arke (network/multi-tenancy) concept was
-- removed. It previously contained:
--   - Adding arke_id column to actors
--   - Renaming network_id to arke_id on entities, groups, spaces
--   - Creating current_actor_arke_id() session helper
--   - Rewriting RLS policies on entities, groups, spaces with arke_id scoping
--   - Rewriting actor_update_guard to add arke_id immutability check
--
-- The actor_update_guard function from 015-rls-policies.sql (without arke_id
-- checks) remains active.
--
-- =============================================================================
