// Copyright (c) 2026 Arkeon Technologies, Inc.
// SPDX-License-Identifier: Apache-2.0

/**
 * Provider registry for skill installation.
 *
 * A "provider" is a target AI coding environment (Claude Code, Codex, Cursor).
 * Each provider knows where to write skills and what format to use.
 */

import { existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

import { output } from "../../lib/output.js";

// Bundled skill content — generated by scripts/bundle-assets.ts
import { SKILLS } from "../../../generated/assets.js";

export interface Provider {
  name: string;
  description: string;
  skillDir: () => string;
  skillFileName: string;
  skillNames: () => string[];
  install: () => { installed: string[]; dir: string };
  uninstall: () => { removed: string[] };
}

// ---------------------------------------------------------------------------
// Claude Code
// ---------------------------------------------------------------------------

const claude: Provider = {
  name: "claude",
  description: "Claude Code (skills in ~/.claude/skills/)",
  skillDir: () => join(homedir(), ".claude", "skills"),
  skillFileName: "SKILL.md",

  skillNames() {
    const skills = SKILLS?.["claude"];
    return skills ? Object.keys(skills) : [];
  },

  install() {
    const dir = this.skillDir();
    const skills = SKILLS?.["claude"] ?? {};
    const installed: string[] = [];

    for (const [name, content] of Object.entries(skills) as [string, string][]) {
      const skillDir = join(dir, name);
      mkdirSync(skillDir, { recursive: true });
      writeFileSync(join(skillDir, this.skillFileName), content);
      installed.push(name);
    }

    return { installed, dir };
  },

  uninstall() {
    const dir = this.skillDir();
    const removed: string[] = [];

    for (const name of this.skillNames()) {
      const skillDir = join(dir, name);
      if (existsSync(skillDir)) {
        rmSync(skillDir, { recursive: true });
        removed.push(name);
      }
    }

    return { removed };
  },
};

// ---------------------------------------------------------------------------
// Codex (stub)
// ---------------------------------------------------------------------------

const codex: Provider = {
  name: "codex",
  description: "OpenAI Codex (coming soon)",
  skillDir: () => "",
  skillFileName: "agent.md",
  skillNames: () => [],
  install() {
    output.progress("Codex provider is not yet implemented. Coming soon.");
    return { installed: [], dir: "" };
  },
  uninstall() {
    output.progress("Codex provider is not yet implemented.");
    return { removed: [] };
  },
};

// ---------------------------------------------------------------------------
// Cursor (stub)
// ---------------------------------------------------------------------------

const cursor: Provider = {
  name: "cursor",
  description: "Cursor (coming soon)",
  skillDir: () => "",
  skillFileName: ".mdc",
  skillNames: () => [],
  install() {
    output.progress("Cursor provider is not yet implemented. Coming soon.");
    return { installed: [], dir: "" };
  },
  uninstall() {
    output.progress("Cursor provider is not yet implemented.");
    return { removed: [] };
  },
};

// ---------------------------------------------------------------------------
// Registry
// ---------------------------------------------------------------------------

export const providers: Record<string, Provider> = {
  claude,
  codex,
  cursor,
};

export function getProvider(name: string): Provider | null {
  return providers[name] ?? null;
}

export function listProviders(): Provider[] {
  return Object.values(providers);
}
