// Copyright (c) 2026 Arkeon Technologies, Inc.
// SPDX-License-Identifier: Apache-2.0

/**
 * Provider registry for skill installation.
 *
 * A "provider" is a target AI coding environment. Each provider knows where
 * to write skills and what format to use.
 *
 * Providers are either global (skills in ~/.<tool>/skills/) or project-local
 * (skills in .cursor/commands/ relative to cwd). The "agents" meta-provider
 * installs all providers at once plus a universal AGENTS.md file.
 */

import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

import { output } from "../../lib/output.js";

// Bundled skill content — generated by scripts/bundle-assets.ts
import { AGENTS_MD, SKILLS } from "../../../generated/assets.js";

export interface Provider {
  name: string;
  description: string;
  /** Where skills are written. Global providers return an absolute path; project-local ones return relative to cwd. */
  skillDir: () => string;
  skillFileName: string;
  /** True = installed to home dir (~/.tool/skills/). False = installed relative to cwd. */
  isGlobal: boolean;
  skillNames: () => string[];
  install: () => { installed: string[]; dir: string };
  uninstall: () => { removed: string[] };
}

const VALID_NAME = /^[a-z0-9][a-z0-9-]*$/;

// ---------------------------------------------------------------------------
// Helpers for skill-dir providers (Claude, Codex, Gemini)
// ---------------------------------------------------------------------------

/** Creates a provider that writes SKILL.md into ~/.<tool>/skills/<name>/ */
function makeSkillDirProvider(
  name: string,
  description: string,
  toolDir: string,
): Provider {
  return {
    name,
    description,
    skillDir: () => join(homedir(), toolDir, "skills"),
    skillFileName: "SKILL.md",
    isGlobal: true,

    skillNames() {
      const skills = SKILLS?.[name];
      return skills ? Object.keys(skills) : [];
    },

    install() {
      const dir = this.skillDir();
      const skills = SKILLS?.[name] ?? {};
      const installed: string[] = [];
      const currentNames = new Set(Object.keys(skills));

      // Remove stale arkeon-* skills from previous versions
      try {
        for (const entry of readdirSync(dir, { withFileTypes: true })) {
          if (entry.isDirectory() && entry.name.startsWith("arkeon-") && !currentNames.has(entry.name)) {
            rmSync(join(dir, entry.name), { recursive: true });
          }
        }
      } catch {
        // dir may not exist yet — that's fine
      }

      for (const [skillName, content] of Object.entries(skills) as [string, string][]) {
        if (!VALID_NAME.test(skillName)) continue;
        const skillDir = join(dir, skillName);
        mkdirSync(skillDir, { recursive: true });
        writeFileSync(join(skillDir, this.skillFileName), content);
        installed.push(skillName);
      }

      return { installed, dir };
    },

    uninstall() {
      const dir = this.skillDir();
      const removed: string[] = [];

      for (const skillName of this.skillNames()) {
        const skillDir = join(dir, skillName);
        if (existsSync(skillDir)) {
          rmSync(skillDir, { recursive: true });
          removed.push(skillName);
        }
      }

      return { removed };
    },
  };
}

// ---------------------------------------------------------------------------
// Claude Code — ~/.claude/skills/<name>/SKILL.md
// ---------------------------------------------------------------------------

const claude = makeSkillDirProvider("claude", "Claude Code (skills in ~/.claude/skills/)", ".claude");

// ---------------------------------------------------------------------------
// Codex CLI — ~/.codex/skills/<name>/SKILL.md
// ---------------------------------------------------------------------------

const codex = makeSkillDirProvider("codex", "OpenAI Codex (skills in ~/.codex/skills/)", ".codex");

// ---------------------------------------------------------------------------
// Gemini CLI — ~/.gemini/skills/<name>/SKILL.md
// ---------------------------------------------------------------------------

const gemini = makeSkillDirProvider("gemini", "Gemini CLI (skills in ~/.gemini/skills/)", ".gemini");

// ---------------------------------------------------------------------------
// Cursor — .cursor/commands/<name>.md (project-local, flat files)
// ---------------------------------------------------------------------------

const cursor: Provider = {
  name: "cursor",
  description: "Cursor (commands in .cursor/commands/)",
  skillDir: () => join(process.cwd(), ".cursor", "commands"),
  skillFileName: ".md",
  isGlobal: false,

  skillNames() {
    const skills = SKILLS?.["cursor"];
    return skills ? Object.keys(skills) : [];
  },

  install() {
    const dir = this.skillDir();
    const skills = SKILLS?.["cursor"] ?? {};
    const installed: string[] = [];
    const currentNames = new Set(Object.keys(skills));

    // Remove stale arkeon-* commands from previous versions
    try {
      for (const entry of readdirSync(dir, { withFileTypes: true })) {
        if (entry.isFile() && entry.name.startsWith("arkeon-") && entry.name.endsWith(".md")) {
          const base = entry.name.replace(/\.md$/, "");
          if (!currentNames.has(base)) {
            rmSync(join(dir, entry.name));
          }
        }
      }
    } catch {
      // dir may not exist yet
    }

    for (const [skillName, content] of Object.entries(skills) as [string, string][]) {
      if (!VALID_NAME.test(skillName)) continue;
      mkdirSync(dir, { recursive: true });
      writeFileSync(join(dir, `${skillName}.md`), content);
      installed.push(skillName);
    }

    return { installed, dir };
  },

  uninstall() {
    const dir = this.skillDir();
    const removed: string[] = [];

    for (const skillName of this.skillNames()) {
      const filePath = join(dir, `${skillName}.md`);
      if (existsSync(filePath)) {
        rmSync(filePath);
        removed.push(skillName);
      }
    }

    return { removed };
  },
};

// ---------------------------------------------------------------------------
// AGENTS.md — universal context file written to project root
// ---------------------------------------------------------------------------

const AGENTS_MD_MARKER = "<!-- arkeon:managed";

/** Write AGENTS.md to the current project root. */
export function installAgentsMd(): boolean {
  if (!AGENTS_MD) return false;
  const dest = join(process.cwd(), "AGENTS.md");
  writeFileSync(dest, AGENTS_MD);
  return true;
}

/** Remove AGENTS.md from the current project root if it's arkeon-managed. */
export function uninstallAgentsMd(): boolean {
  const dest = join(process.cwd(), "AGENTS.md");
  if (!existsSync(dest)) return false;
  try {
    const content = readFileSync(dest, "utf-8");
    if (!content.includes(AGENTS_MD_MARKER)) return false;
    rmSync(dest);
    return true;
  } catch {
    return false;
  }
}

/** Check if an arkeon-managed AGENTS.md exists in cwd. */
export function hasArkeonAgentsMd(): boolean {
  const dest = join(process.cwd(), "AGENTS.md");
  if (!existsSync(dest)) return false;
  try {
    const content = readFileSync(dest, "utf-8");
    return content.includes(AGENTS_MD_MARKER);
  } catch {
    return false;
  }
}

// ---------------------------------------------------------------------------
// Agents — meta-provider that installs everything
// ---------------------------------------------------------------------------

/** Individual providers (not including the "agents" meta-provider). */
export const individualProviders: Provider[] = [claude, codex, cursor, gemini];

const agents: Provider = {
  name: "agents",
  description: "All AI coding tools (Claude, Codex, Cursor, Gemini + AGENTS.md)",
  skillDir: () => "",
  skillFileName: "",
  isGlobal: false,

  skillNames() {
    return [...new Set(individualProviders.flatMap((p) => p.skillNames()))];
  },

  install() {
    const allInstalled: string[] = [];
    const dirs: string[] = [];

    for (const provider of individualProviders) {
      try {
        const { installed, dir } = provider.install();
        allInstalled.push(...installed.map((s) => `${provider.name}/${s}`));
        if (dir) dirs.push(dir);
      } catch (err) {
        output.progress(`Warning: failed to install ${provider.name} skills: ${(err as Error).message}`);
      }
    }

    // Write AGENTS.md
    if (installAgentsMd()) {
      allInstalled.push("AGENTS.md");
      dirs.push(process.cwd());
    }

    return { installed: allInstalled, dir: dirs.join(", ") };
  },

  uninstall() {
    const allRemoved: string[] = [];

    for (const provider of individualProviders) {
      try {
        const { removed } = provider.uninstall();
        allRemoved.push(...removed.map((s) => `${provider.name}/${s}`));
      } catch {
        // best-effort
      }
    }

    if (uninstallAgentsMd()) {
      allRemoved.push("AGENTS.md");
    }

    return { removed: allRemoved };
  },
};

// ---------------------------------------------------------------------------
// Registry
// ---------------------------------------------------------------------------

export const providers: Record<string, Provider> = {
  agents,
  claude,
  codex,
  cursor,
  gemini,
};

export function getProvider(name: string): Provider | null {
  return Object.hasOwn(providers, name) ? providers[name]! : null;
}

export function listProviders(): Provider[] {
  return Object.values(providers);
}
