-- =============================================================================
-- SPEC: Invitation Codes
-- =============================================================================
-- Status: DESIGN SPEC — not executable SQL. Comments describe intent.
--
-- CONCEPT:
-- Invitation codes bridge "stranger" → "registered actor." An actor with
-- invite permission generates a code. The holder registers with it.
-- Codes are usage-limited and expire.
--
-- =============================================================================
-- TABLE: invitations
-- =============================================================================
--
-- CREATE TABLE invitations (
--   code             TEXT PRIMARY KEY,          -- crypto-random (32 bytes hex)
--   network_id       TEXT NOT NULL              -- root commons ID
--                     REFERENCES entities(id),
--   created_by       TEXT NOT NULL              -- actor who generated the code
--                     REFERENCES entities(id),
--   max_uses         INT NOT NULL DEFAULT 1,   -- how many times code can be used
--   uses             INT NOT NULL DEFAULT 0,   -- how many times it has been used
--   assign_groups    TEXT[] NOT NULL DEFAULT '{}',  -- group IDs to auto-add on registration
--   expires_at       TIMESTAMPTZ,              -- NULL = never expires
--   bound_public_key TEXT,                     -- if set, only this pubkey can redeem
--   created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
-- );
--
-- =============================================================================
-- REDEMPTION FLOW
-- =============================================================================
--
-- When a code is redeemed during POST /auth/register:
--
--   1. Validate:
--      - Code exists (else 404)
--      - uses < max_uses (else 410 "Invitation code exhausted")
--      - expires_at IS NULL OR expires_at > NOW() (else 410 "Expired")
--      - bound_public_key IS NULL OR matches registrant's key (else 403)
--
--   2. Consume atomically:
--      UPDATE invitations SET uses = uses + 1
--      WHERE code = $1 AND uses < max_uses
--      RETURNING *
--      (If 0 rows returned, code was consumed by concurrent request — 410)
--
--   3. Add registrant to groups:
--      INSERT INTO group_memberships (group_id, actor_id, granted_by)
--      SELECT unnest(assign_groups), $new_actor_id, $invitation_created_by
--
-- =============================================================================
-- INVITE PERMISSION
-- =============================================================================
--
-- Who can generate invite codes?
--
--   1. Network admins (always):
--      EXISTS(SELECT 1 FROM entity_access
--             WHERE entity_id = ROOT_COMMONS_ID
--               AND actor_id = current_actor_id()
--               AND access_type = 'admin')
--
--   2. Members of any group where can_invite = true:
--      EXISTS(SELECT 1 FROM group_memberships gm
--             JOIN groups g ON g.id = gm.group_id
--             WHERE gm.actor_id = current_actor_id()
--               AND g.can_invite = true)
--
-- GROUP ASSIGNMENT CONSTRAINT:
--   Non-admin actors can only assign groups they belong to (effective groups).
--   Admins can assign any group.
--
--   Validation: for non-admins, every group in assign_groups must appear in
--   actor_effective_groups(current_actor_id()).
--
-- =============================================================================
-- RLS ON THIS TABLE
-- =============================================================================
--
-- SELECT: Actors see their own invitations. Admins see all.
--   created_by = current_actor_id()
--   OR EXISTS(admin check on root commons)
--
-- INSERT: Must have invite permission (see above).
-- UPDATE: Not allowed (codes are immutable after creation).
-- DELETE: Creator or admin.
--
-- =============================================================================
-- API ENDPOINTS
-- =============================================================================
--
-- POST /invitations
--   Auth: required (must have invite permission)
--   Body: {
--     max_uses?:         number,     -- default 1
--     assign_groups?:    string[],   -- group IDs to auto-add
--     expires_in?:       number,     -- seconds until expiry (convenience)
--     expires_at?:       string,     -- ISO 8601 absolute expiry
--     bound_public_key?: string      -- lock to specific key (optional)
--   }
--   Validation:
--     - max_uses >= 1
--     - expires_in and expires_at mutually exclusive
--     - assign_groups: each must be existing group; non-admin can only
--       assign groups they belong to
--   Response 201: { code, max_uses, assign_groups, expires_at, created_at }
--
-- GET /invitations
--   Auth: required
--   Returns own invitations (or all if admin).
--   Response 200: { invitations: [...] }
--
-- DELETE /invitations/:code
--   Auth: required (creator or admin)
--   Response 204
--
-- =============================================================================
-- CHANGES TO AUTH REGISTRATION
-- =============================================================================
--
-- POST /auth/register — updated request body:
--   {
--     public_key:       string,    -- Ed25519 public key (hex)
--     nonce?:           string,    -- required if mode=open
--     signature:        string,    -- of nonce (open) or invitation_code (invite_only)
--     solution?:        number,    -- required if mode=open
--     invitation_code?: string,    -- required if mode=invite_only
--     name?:            string,
--     metadata?:        object
--   }
--
-- FLOW (invite_only):
--   1. Require invitation_code (else 400)
--   2. Validate code (see redemption flow above)
--   3. Verify signature of invitation_code (proves key ownership)
--   4. Skip PoW
--   5. Create agent entity
--   6. Consume code (atomic uses increment)
--   7. Add to groups from assign_groups
--   8. Return entity + api_key
--
-- FLOW (open):
--   1. Existing PoW + Ed25519 flow
--   2. If invitation_code provided: validate, consume, add to groups
--   3. Return entity + api_key
--
-- =============================================================================
