// Copyright (c) 2026 Arkeon Technologies, Inc.
// SPDX-License-Identifier: Apache-2.0

/**
 * Reads the Genesis seed envelope from packages/cli/assets/seeds/ and
 * emits a single TypeScript module at packages/cli/src/generated/assets.ts
 * exporting it as a typed object literal.
 *
 * The generated module is committed (same pattern as src/generated/index.ts)
 * so the package builds without an out-of-band copy step and the bundled
 * payload is reviewable in PR diffs.
 *
 * Wired into `npm run build` ahead of tsup. tsup then inlines the generated
 * module into dist/index.js, so the published npm package needs no separate
 * assets directory at runtime for the seed.
 */

import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const cliRoot = join(__dirname, "..");

const genesisOpsPath = join(cliRoot, "assets", "seeds", "genesis-creation.ops.json");

const outputPath = join(cliRoot, "src", "generated", "assets.ts");

function readText(path: string): string {
  try {
    return readFileSync(path, "utf8");
  } catch (error) {
    throw new Error(`bundle-assets: failed to read ${path}: ${(error as Error).message}`);
  }
}

function readJson(path: string): unknown {
  const text = readText(path);
  try {
    return JSON.parse(text);
  } catch (error) {
    throw new Error(`bundle-assets: ${path} is not valid JSON: ${(error as Error).message}`);
  }
}

const genesisOps = readJson(genesisOpsPath);

// ---------------------------------------------------------------------------
// Skills — walk assets/skills/<provider>/<skill-name>/SKILL.md
// ---------------------------------------------------------------------------

const skillsDir = join(cliRoot, "assets", "skills");
const skills: Record<string, Record<string, string>> = {};

try {
  for (const provider of readdirSync(skillsDir, { withFileTypes: true })) {
    if (!provider.isDirectory()) continue;
    const providerDir = join(skillsDir, provider.name);
    skills[provider.name] = {};
    for (const skill of readdirSync(providerDir, { withFileTypes: true })) {
      if (!skill.isDirectory()) continue;
      const skillFile = join(providerDir, skill.name, "SKILL.md");
      try {
        skills[provider.name]![skill.name] = readText(skillFile);
      } catch {
        // Skip skills without SKILL.md
      }
    }
  }
} catch {
  // assets/skills/ doesn't exist yet — no skills to bundle
}

// ---------------------------------------------------------------------------
// Emit
// ---------------------------------------------------------------------------

const banner = `// AUTO-GENERATED by scripts/bundle-assets.ts — do not edit.
// Re-generate with \`npm run bundle-assets -w packages/arkeon\` (also runs as
// part of \`npm run build -w packages/arkeon\`).
//
// Source files:
//   - genesis-creation.ops.json <- assets/seeds/
//   - skills/**  <- assets/skills/<provider>/<skill>/SKILL.md
`;

const skillEntries = Object.entries(skills)
  .map(([provider, providerSkills]) => {
    const entries = Object.entries(providerSkills)
      .map(([name, content]) => `    ${JSON.stringify(name)}: ${JSON.stringify(content)}`)
      .join(",\n");
    return `  ${JSON.stringify(provider)}: {\n${entries}\n  }`;
  })
  .join(",\n");

const body = `${banner}
/**
 * arke.ops/v1 envelope ready to POST to /ops. Typed loosely so consumers
 * (e.g. \`arkeon seed\`) don't have to depend on the API's full ops schema.
 */
export const GENESIS_OPS: { format: string; ops: Array<Record<string, unknown>> } = ${JSON.stringify(genesisOps)};

/**
 * Bundled skills keyed by provider → skill-name → SKILL.md content.
 * Used by \`arkeon install <provider>\` to write skills to the target directory.
 */
export const SKILLS: Record<string, Record<string, string>> = {
${skillEntries}
};
`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, body);

console.log(`bundle-assets: wrote ${outputPath}`);
console.log(`  genesis-creation.ops.json: ${(JSON.stringify(genesisOps) as string).length} bytes (parsed)`);
const skillCount = Object.values(skills).reduce((n, s) => n + Object.keys(s).length, 0);
console.log(`  skills: ${skillCount} across ${Object.keys(skills).length} provider(s)`);
