// Copyright (c) 2026 Arkeon Technologies, Inc.
// SPDX-License-Identifier: Apache-2.0

/**
 * Reads the CLI-local docker-compose.yml (the image-based one that ships to
 * end users) plus .env.example from the repo root and the Genesis seed
 * envelope from packages/cli/assets/seeds/, and emits a single TypeScript
 * module at packages/cli/src/generated/assets.ts exporting them as string /
 * object constants.
 *
 * The CLI-local compose file (packages/cli/assets/docker-compose.yml) uses
 * `image: ghcr.io/...` + `command:` overrides so users who run
 * `arkeon init` from an empty directory don't need to clone the repo. The
 * repo-root compose file uses `build: { context: ., target: ... }` for
 * contributors running `docker compose up` from a git checkout — the two
 * stay intentionally distinct.
 *
 * The generated module is committed (same pattern as src/generated/index.ts)
 * so the package builds without an out-of-band copy step and the bundled
 * payload is reviewable in PR diffs.
 *
 * Wired into `npm run build` ahead of tsup. tsup then inlines the generated
 * module into dist/index.js, so the published npm package needs no separate
 * assets directory at runtime.
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const cliRoot = join(__dirname, "..");
const repoRoot = join(cliRoot, "..", "..");

const dockerComposePath = join(cliRoot, "assets", "docker-compose.yml");
const envExamplePath = join(repoRoot, ".env.example");
const genesisOpsPath = join(cliRoot, "assets", "seeds", "genesis-creation.ops.json");

const outputPath = join(cliRoot, "src", "generated", "assets.ts");

function readText(path: string): string {
  try {
    return readFileSync(path, "utf8");
  } catch (error) {
    throw new Error(`bundle-assets: failed to read ${path}: ${(error as Error).message}`);
  }
}

function readJson(path: string): unknown {
  const text = readText(path);
  try {
    return JSON.parse(text);
  } catch (error) {
    throw new Error(`bundle-assets: ${path} is not valid JSON: ${(error as Error).message}`);
  }
}

const dockerComposeYml = readText(dockerComposePath);
const envExample = readText(envExamplePath);
const genesisOps = readJson(genesisOpsPath);

const banner = `// AUTO-GENERATED by scripts/bundle-assets.ts — do not edit.
// Re-generate with \`npm run bundle-assets -w packages/cli\` (also runs as
// part of \`npm run build -w packages/cli\`).
//
// Source files:
//   - docker-compose.yml      <- repo root
//   - .env.example            <- repo root
//   - genesis-creation.ops.json <- packages/cli/assets/seeds/
`;

const body = `${banner}
export const DOCKER_COMPOSE_YML = ${JSON.stringify(dockerComposeYml)};

export const ENV_EXAMPLE = ${JSON.stringify(envExample)};

/**
 * arke.ops/v1 envelope ready to POST to /ops. Typed loosely so consumers
 * (e.g. \`arkeon seed\`) don't have to depend on the API's full ops schema.
 */
export const GENESIS_OPS: { format: string; ops: Array<Record<string, unknown>> } = ${JSON.stringify(genesisOps)};
`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, body);

console.log(`bundle-assets: wrote ${outputPath}`);
console.log(`  docker-compose.yml: ${dockerComposeYml.length} bytes`);
console.log(`  .env.example: ${envExample.length} bytes`);
console.log(`  genesis-creation.ops.json: ${(JSON.stringify(genesisOps) as string).length} bytes (parsed)`);
